const authActionTypes = {
  USER_INFO_SYNC: 'USER_INFO_SYNC',

  LOGOUT_SUCCEED: 'LOGOUT_SUCCEED',
  LOGOUT_FAIL: 'LOGOUT_FAIL',

  SIGNUP_SUCCEED: 'SIGNUP_SUCCEED',
  BASIC_LOGIN_SUCCEED: 'BASIC_LOGIN_SUCCEED',
  FACEBOOK_LOGIN_SUCCEED: 'FACEBOOK_LOGIN_SUCCEED',
};

export default authActionTypes;
